# Generated by Django 6.0.3 on 2026-04-25 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer lokalu'),
        ),
        migrations.AddField(
            model_name='listing',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer budynku'),
        ),
        migrations.AddField(
            model_name='listing',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location', verbose_name='Miasto'),
        ),
    ]
