# Generated by Django 6.0.3 on 2026-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_listing_apartment_number_listing_building_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='delivery_methods',
            field=models.ManyToManyField(blank=True, to='api.deliverymethod', verbose_name='Metody dostawy'),
        ),
    ]
