# Generated by Django 6.0.3 on 2026-04-25 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_listing_delivery_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ulica')),
                ('building_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nr budynku')),
                ('apartment_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nr mieszkania')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.location', verbose_name='Lokalizacja (Miasto)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
    ]
