# Generated by Django 6.0.3 on 2026-05-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Zamówienie', 'verbose_name_plural': 'Zamówienia'},
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Cena ogłoszenia w momencie kliknięcia 'Kup teraz'", max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('PAID', 'Opłacone'), ('SHIPPED', 'Wysłane'), ('COMPLETED', 'Zakończone'), ('CANCELLED', 'Anulowane')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_details',
            field=models.TextField(blank=True, help_text='Dane adresowe, numer paczkomatu itp.', null=True),
        ),
    ]
