# Generated by Django 6.0.3 on 2026-06-06 21:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_address_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[api.models.validate_address_number], verbose_name='Numer lokalu'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[api.models.validate_address_number], verbose_name='Numer budynku'),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[api.models.validate_street], verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[api.models.validate_address_number], verbose_name='Numer lokalu'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='building_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[api.models.validate_address_number], verbose_name='Numer budynku'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(default='bwa', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[api.models.validate_street], verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='listingstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
