# Generated by Django 6.0.3 on 2026-06-06 22:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_address_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.CharField(error_messages={'blank': 'Numer lokalu nie może składać się z samych spacji.'}, max_length=20, null=True, validators=[api.models.validate_address_number], verbose_name='Numer lokalu'),
        ),
        migrations.AlterField(
            model_name='address',
            name='building_number',
            field=models.CharField(error_messages={'blank': 'Numer budynku nie może składać się z samych spacji.'}, max_length=20, null=True, validators=[api.models.validate_address_number], verbose_name='Numer budynku'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(error_messages={'blank': 'Ulica nie może składać się z samych spacji.'}, max_length=255, null=True, validators=[api.models.validate_street], verbose_name='Ulica'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='apartment_number',
            field=models.CharField(error_messages={'blank': 'Numer lokalu nie może składać się z samych spacji.'}, max_length=20, null=True, validators=[api.models.validate_address_number], verbose_name='Numer lokalu'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='building_number',
            field=models.CharField(error_messages={'blank': 'Numer budynku nie może składać się z samych spacji.'}, max_length=20, null=True, validators=[api.models.validate_address_number], verbose_name='Numer budynku'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='street',
            field=models.CharField(error_messages={'blank': 'Ulica nie może składać się z samych spacji.'}, max_length=255, null=True, validators=[api.models.validate_street], verbose_name='Ulica'),
        ),
    ]
