# Generated by Django 6.0.3 on 2026-06-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_address_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='location',
            field=models.ForeignKey(default=202, on_delete=django.db.models.deletion.PROTECT, to='api.location', verbose_name='Lokalizacja (Miasto)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_num',
            field=models.CharField(default='123456789', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='delivery_methods',
            field=models.ManyToManyField(to='api.deliverymethod', verbose_name='Metody dostawy'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(default=202, on_delete=django.db.models.deletion.PROTECT, to='api.location', verbose_name='Miasto'),
            preserve_default=False,
        ),
    ]
